### ISSUE TITLE
Add more specific file extensions

### ISSUE THREAD

**Issue by mlf-inde** [GSGBen/fortigate-fortios-syntax#1]
Currently this extension is only mapping Fortigate language to file extension .conf.
This .conf is commonly used across many usages, therefore is in conflict with other VScode syntax highlighting extensions.

I am proposing that some very specific file extensions be added to this extension e.g. ".fgt", ".fortigate" that will not be in conflict with other config files in the user's system.

**Comment by GSGBen** [comment]
Hey, thanks for reaching out.

This sounds reasonable. I've added `.fortigate` and `.fgt` on version 1.1.0. It should be live in a bit. I've kept `.conf` as the default save extension as that's the one used by the FortiGate GUI.
